spring.application.name=demo
server.port=8080

# --- MULTIPART SAZLAMALARI (??kill?r üçün) ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# --- JWT TOKEN SECRET KEY ---
application.jwt.spring.token=YjY5Z2I1dzRzNmU4cjN0MXk3dTlvMHA5YThzN2Q2ZjVnNGgzajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YY==

# --- H2 DATABASE BAZA BA?LANTISI ---
spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=1234

# --- HIBERNATE & JPA AYARLARI ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- SKR?PT?N ÇÖKM?M?S? ÜÇÜN ?SAS S?T?R ---
# Hibernate c?dv?ll?ri tam yaradandan sonra data.sql fayl?n? i?l?dir
spring.jpa.defer-datasource-initialization=true

# --- H2 CONSOLE AKT?VL??D?R?LM?S? ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true