spring.application.name=demo


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

application.jwt.spring.token=YjY5Z2I1dzRzNmU4cjN0MXk3dTlvMHA5YThzN2Q2ZjVnNGgzajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YY==

server.port=8080

#spring.datasource.url=jdbc:h2:mem:demo
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=1234


# db yerin? localhost yaz?r?q
spring.datasource.url=jdbc:mysql://localhost:5000/final_project?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=!@#$%^&*(123456789sabir
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialekt-i ?l il? göst?r ki, Hibernate naz el?m?sin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never



spring.jpa.defer-datasource-initialization=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
